---
title: "Analysis pipeline of applying XConTest for Gene Module Convergence Test"
author: "Tianyu Zhang, Ergan Shang and Kathryn Roeder"
format: html
editor: visual
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(HMC)
library(MASS)
library(ggplot2)
library(patchwork)
library(dplyr)
library(reshape2)
library(pheatmap)
library(ggnewscale)
library(highmean)

work_directory <- here::here()
code_directory <- paste0(work_directory, '/converge_by_module/code')
code_directory |> print()
```

### Create the Heatmap

```{r, eval = FALSE}
source(file.path(code_directory, '01_poisson_eff.R'),
       local = TRUE)
```

### Perform XConTest Analysis on Artificial Perturbation Data

```{r, eval = FALSE}
source(file.path(code_directory, '02_test_raw_count_1se_200_400_standardize.R'),
       local = TRUE)
```

### Create the Results of XConTest

```{r, eval = FALSE}
source(file.path(code_directory, '03_draw_test_raw_count_1se_200_400_standardize.R'),
       local = TRUE)
```

### Perform Dset Analysis on Artificial Perturbation Data

```{r, eval = FALSE}
source(file.path(code_directory, '04_bm_Chen.R'),
       local = TRUE)
```

### Create the Results of Dset

```{r, eval = FALSE}
source(file.path(code_directory, '05_bm_Chen_draw.R'),
       local = TRUE)
```